[[pages]]
path = "app.py"
name = "Home"
icon = "ğŸ "

[[pages]]
path = "old/app4.py"
name = "DashboardAIFINA"
icon = "ğŸ’°"

[[pages]]
path = "old/app2.py"
name = "DashboardCEO"
icon = "ğŸ“Š"

[[pages]]
path = "old/app5.py"
name = "DashboardCEOAnalysis"
icon = "ğŸ’°"

[[pages]]
path = "old/app3.py"
name = "Key Performance Indicators"
icon = "ğŸ“ˆ"

[[pages]]
path = "oldv2/dashboard.py"
name = "DashboardCEOAnalysis"
icon = "ğŸ’°"
